services:
  web:
    image: ${APP_IMAGE}              # ← 여기만 변수로 주입
    env_file:
      - ../.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod     # ✅ prod 강제
      - PYTHONUNBUFFERED=1
    command: ["gunicorn","config.wsgi:application","-b","0.0.0.0:8000","-w","3","--timeout","90","--log-file","-"]  # ✅ stdout로 로그
    volumes:
      - static_volume:/app/staticfiles
    healthcheck:                                        # ✅ 재시작 루프 가시화/제어
      test: ["CMD-SHELL","python - <<'PY'\nimport socket; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1',8000)); print('ok')\nPY"]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 20s
    networks: [app_net]
    restart: unless-stopped

  nginx:
    image: nginx:1.27                # 고정 이미지 (치환 금지)
    ports:
      - "80:80"
      - "443:443"  # ✅ HTTPS 포트 추가
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_conf:/etc/letsencrypt  # ✅ Certbot 설정 볼륨
      - certbot_www:/var/www/certbot   # ✅ Certbot 인증용 볼륨
    depends_on:
      web:
        condition: service_healthy 
    networks: [app_net]
    restart: unless-stopped

  # ✅ Certbot 서비스 추가 (인증서 발급/갱신용)
  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: ["--version"] # 평소에는 실행되지 않도록 더미 명령 설정

volumes:
  static_volume:
  certbot_conf:
  certbot_www:

networks:
  app_net:
