services:
  web:
    image: ${APP_IMAGE}              # ← 여기만 변수로 주입
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod     # ✅ prod 강제
      - PYTHONUNBUFFERED=1
    command: ["gunicorn","config.wsgi:application","-b","0.0.0.0:8000","-w","3","--timeout","90","--log-file","-"]  # ✅ stdout로 로그
    volumes:
      - static_volume:/app/staticfiles
    healthcheck:                                        # ✅ 재시작 루프 가시화/제어
      test: ["CMD-SHELL","python - <<'PY'\nimport socket; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1',8000)); print('ok')\nPY"]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 20s
    networks: [app_net]
    restart: unless-stopped

  nginx:
    image: nginx:1.27                # 고정 이미지 (치환 금지)
    ports: ["80:80"]
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      web:
        condition: service_healthy 
    networks: [app_net]
    restart: unless-stopped

volumes:
  static_volume:

networks:
  app_net:
