version: "3.9"
services:
  web:
    image: ${APP_IMAGE}     # ← 배포 스크립트가 주입
    env_file:
      - ../.env
    command: ["gunicorn","config.wsgi:application","-b","0.0.0.0:8000","-w","3"]
    volumes:
      - static_volume:/app/staticfiles
    networks: [app_net]
    restart: unless-stopped

  nginx:
    image: nginx:1.27       # ← 고정 (치환 금지)
    ports: ["80:80"]
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [web]
    networks: [app_net]
    restart: unless-stopped

volumes:
  static_volume:

networks:
  app_net:

